name: Build and Test

on:
  push:
    branches: [ main, hamdi ]
  pull_request:
    branches: [ main, hamdi ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm test
          cd ../backend
          npm test

      - name: Build project
        run: |
          cd frontend
          npm run build
          cd ../backend
          npm run build
