name: Backend CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - hamdi  # Ajout de ta branche spécifique
  pull_request:
    branches:
      - main

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        working-directory: backend
        run: npm install 

      - name: Run linting
        working-directory: backend
        run: npm run lint

      - name: Run tests
        working-directory: backend
        run: npm test

      - name: Build project
        working-directory: backend
        run: npm run build --if-present
